### PR TITLE
WCMS-1072: Added datetime fixer for header time

### PR DESCRIPTION
**Pull request by sshobotov**
https://nzzdev.atlassian.net/browse/WCMS-1072

### CODE REVIEW

**Comment by sshobotov** [comment]
@DaRaFF, @marcbachmann please review

**Comment by DaRaFF** [comment]
the name post-datetime-attribut-fixer seems strange to me, it intends there is something wrong. In my opinion its a datetime-morpheus-formatter, because its converting to the correct output format.

**Comment by DaRaFF** [comment]
the name post-datetime-attribut-fixer seems strange to me, it intends there is something wrong. In my opinion its a datetime-morpheus-formatter, because its converting to the correct output format.

**Comment by DaRaFF** [comment]
the rest looks fine

**Comment by sshobotov** [comment]
I like to prefix all middlewares with "post" or "pre" to be sure about its scope without looking into code. And about "datetime-morpheus-formatter" we format date in usual for PHP time format, there is nothing specific for morpheus.

**Comment by DaRaFF** [comment]
yeah, but your formatter should expose what he does. So you should say for what channel or format he is formatting for.

When the format is not morpheus specific you could call it `post-nzz-datetime-formatter`, because we want to create a general nzz datetime output.

**Comment by sshobotov** [comment]
But all of render decorator middlewares are just for nzz:)

**Comment by mheiniger** [comment]
then how about just post-datetime-formatter?

**Comment by sshobotov** [comment]
good for me

**Comment by DaRaFF** [comment]
ok

**Comment by sshobotov** [comment]
@DaRaFF files renamed

**Pull request merged**
