### PR TITLE
WCMS-1085: Added decorator to set publication date in HTML

### PR DESCRIPTION
**Pull request by sshobotov**
https://nzzdev.atlassian.net/browse/WCMS-1045

### CODE REVIEW

**Comment by sshobotov** [comment]
@DaRaFF, @gabrielhase, @marcbachmann review please

**Comment by mheiniger** [comment]
While its a working solution for now, the question is, how do we fix such fields in future? Shouldn't that be done in the editor to set a correct publication date, and a data migration task to fix wrong articles?

**Comment by sshobotov** [comment]
For now publication date is set just on publication but not when editing document, so the most appropriate place to make it appear is in render decorator. I think in future we will have some templates that on backend will be filled with data, but for now I think it's ok.

**Comment by gabrielhase** [comment]
A nice option for this would be to have a `doc-date` directive on the engine. But I think the POs wouldn't be happy with the estimation for this :smile:

**Comment by sshobotov** [comment]
Nice idea, but yeah, not for the end of sprint, but we could create a technical task and fix it in next sprint.

**Pull request merged**
